# https://docs.codecov.com/docs/pull-request-comments#disable-comment
comment: false

# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    changes: true
    patch: true
    project:
      default: true
      tests:
        target: auto
        threshold: 1
        paths:
          - "src/"
