name: Deploy Builds

on:
  release:
    types: [ released ]
  push:
    tags:
      - 'v*.*.*rc*'  # for testing releases
      - 'v*.*.*dev*'  # for testing releases

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/pytest.yml
    secrets: inherit

  wheel:
    name: Build wheel
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: clone sorunlib
      uses: actions/checkout@v6

    - name: install build dependencies
      run: |
        python3 -m pip install --upgrade build

    - name: build wheel
      run: |
        python3 -m build

    - name: find wheel
      id: find
      run: |
        WHEEL_FILE=$(ls dist/*.whl)
        echo "::set-output name=wheel::${WHEEL_FILE}"

    - name: install wheel
      run: |
        python3 -m pip install ${{ steps.find.outputs.wheel }}[dev]

    - name: run unit tests
      working-directory: ./tests
      run: |
        python3 -m pytest

    - name: upload dist
      uses: actions/upload-artifact@v6
      with:
        path: ./dist/

  pypi-publish:
    name: Upload release to PyPI
    needs: wheel
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sorunlib
    permissions:
      id-token: write  # required for trusted publishing
    steps:
    - name: download dist
      uses: actions/download-artifact@v5
      with:
        path: dist

    - name: publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
